#!/usr/bin/env python3
"""
Bake the road changes from overrides.json into the itinerary, permanently.

    cd tools && python3 apply_overrides.py

overrides.json is the layer the dashboard reads at load, so a change published
from a phone shows up on every device within a minute. That is the right
mechanism for a change made yesterday. It is the wrong place for a change to
live for eighteen months: the overrides never get the derived work done for
them, so a stop with two extra nights still shows the old light times, the old
booking window and the old cost, and nothing warns you.

This applies them for real — the dates move in STOPS and EXT_DATA, the booking
cards follow — and then empties overrides.json so the same change cannot be
applied twice. Everything downstream is regenerated by the build steps that run
after it.

  nights: +N / -N   the stop gains or loses nights; every later stop shifts
  skip: true        the stop is removed; its nights go back to the trip
  camp: "name"      the campground changes, and the booking card follows

A stop proposed on the road but never researched is deliberately NOT here.
Those arrive through the build with their campground, road, seasonal and drone
data done, or they do not arrive at all.

Standard library only; no network.
"""
import json, pathlib, re, sys, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'desktop' / 'index.html'
OVR = ROOT / 'overrides.json'


def ex(hh, decl, o='{', c='}'):
    i = hh.index(decl); s = hh.index(o, i); d = 0; ins = False; esc = False
    for j in range(s, len(hh)):
        ch = hh[j]
        if ins:
            if esc: esc = False
            elif ch == '\\': esc = True
            elif ch == '"': ins = False
        else:
            if ch == '"': ins = True
            elif ch == o: d += 1
            elif ch == c:
                d -= 1
                if d == 0: return hh[s:j + 1]
    raise ValueError('unterminated: ' + decl)


def shift(iso, days):
    d = datetime.date.fromisoformat(iso) + datetime.timedelta(days=days)
    return d.isoformat()


def apply_to(stops, ovr, log):
    """Walk the trip in order, carrying the accumulated drift."""
    drift, out, dropped = 0, [], []
    for s in stops:
        o = ovr.get(s['id']) or {}
        if o.get('skip'):
            dropped.append((s['id'], s['name'], s.get('nights', 0)))
            drift -= s.get('nights', 0)
            continue
        extra = int(o.get('nights') or 0)
        if drift:
            s['arrive'] = shift(s['arrive'], drift)
        drift += extra
        if extra:
            s['nights'] = (s.get('nights') or 0) + extra
            log.append(f"  {s['id']}: {extra:+d} night(s) -> {s['nights']}")
        if drift:
            s['depart'] = shift(s['depart'], drift)
        if o.get('camp'):
            log.append(f"  {s['id']}: campground {s.get('camp')} -> {o['camp']}")
            s['camp'] = o['camp']
        out.append(s)
    for sid, name, n in dropped:
        log.append(f"  {sid}: DROPPED ({n} night(s) returned) — {name}")
    return out, drift, dropped


def main():
    if not OVR.exists():
        print('  no overrides.json — nothing to apply'); return
    ovr_doc = json.loads(OVR.read_text())
    ovr = ovr_doc.get('stops') or {}
    if not ovr:
        print('  overrides.json is empty — nothing to apply'); return

    h = SRC.read_text()
    stops_raw = ex(h, 'const STOPS =', '[', ']')
    stops = json.loads(stops_raw)
    ext_raw = ex(h, 'const EXT_DATA =')
    ext = json.loads(ext_raw)
    bk_raw = ex(h, 'const BOOKINGS =', '[', ']')
    bookings = json.loads(bk_raw)

    known = {s['id'] for s in stops} | {s['id'] for s in ext['STOPS']}
    unknown = [k for k in ovr if k not in known]
    if unknown:
        sys.exit('!! overrides.json names stops that do not exist: ' + ', '.join(unknown))

    log = []
    stops, drift_main, dropped_main = apply_to(stops, ovr, log)
    ext['STOPS'], drift_ext, dropped_ext = apply_to(ext['STOPS'], ovr, log)

    if not log:
        print('  overrides.json changed nothing'); return

    # Booking cards carry their own copy of the dates and the campground.
    gone = {sid for sid, _, _ in dropped_main + dropped_ext}
    by_stop = {s['id']: s for s in stops + ext['STOPS']}
    bookings = [b for b in bookings if b['id'] not in gone]
    for b in bookings:
        s = by_stop.get(b['id'])
        if not s:
            continue
        if b.get('arrive') != s['arrive'] or b.get('depart') != s['depart']:
            b['arrive'], b['depart'] = s['arrive'], s['depart']
            b['nights'] = s.get('nights')
        if s.get('camp') and b.get('camp') != s['camp']:
            b['camp'] = s['camp']

    h = h.replace(stops_raw, json.dumps(stops, ensure_ascii=False), 1)
    h = h.replace(ext_raw, json.dumps(ext, ensure_ascii=False, indent=1), 1)
    h = h.replace(bk_raw, json.dumps(bookings, ensure_ascii=False), 1)
    SRC.write_text(h)

    # Emptied, or the next run applies the same shift again on top of itself.
    OVR.write_text(json.dumps({
        '_what': ovr_doc.get('_what', 'Plan changes made on the road.'),
        '_shape': ovr_doc.get('_shape', 'stopId -> { nights: +N | -N, skip: true, camp: "name" }'),
        '_applied': datetime.date.today().isoformat(),
        'updated': None,
        'stops': {},
    }, ensure_ascii=False, indent=2) + '\n')

    print(f"  applied {len(ovr)} override(s):")
    for line in log:
        print(line)
    print(f"  net shift: main {drift_main:+d} day(s), east {drift_ext:+d} day(s)")
    print(f"  {len(gone)} stop(s) dropped, {len(bookings)} booking cards left")
    print('  overrides.json emptied so this cannot be applied twice')


if __name__ == '__main__':
    main()
