#!/usr/bin/env python3
"""
Every open question that a phone call would settle, in one list, in date order.

    cd tools && python3 build_calls.py            # print it
    cd tools && python3 build_calls.py --write    # also write CALLS.md

Why this exists
---------------
The research keeps producing the same shape of answer: "the authority publishes
nothing, and this number would settle it." Those findings were landing scattered
across links_db.json — inside a dogs_unpublished block on one stop, inside an
offroad note on another, inside a trail's stats_note on a third. Individually
each one is a sentence someone will never find again. Together they are a short
list of calls that would close out a large fraction of what is still unknown
about the trip.

Ordering is by ARRIVAL DATE, not by stop id, because that is the only order that
matters: a call about Dawson City in August 2027 is worth making before one
about Asheville in December 2028, and a call about a stop three weeks out is
urgent in a way the same call two years out is not.

Standard library only; no network. Reads the built page for dates and the db for
the findings, so it cannot drift from either.
"""
import json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / 'desktop' / 'index.html'
DB = HERE / 'links_db.json'

# A leading \b sits between "(" and "9" and so ate the opening bracket, printing
# "907) 459-7307". Match the bracketed and bare forms explicitly instead.
PHONE = re.compile(r'(?:\+?1[-.\s])?(?:\(\d{3}\)\s?|\d{3}[-.\s])\d{3}[-.\s]\d{4}')


def ex(hh, decl, o='[', c=']'):
    i = hh.index(decl); s = hh.index(o, i); d = 0; ins = False; esc = False
    for j in range(s, len(hh)):
        ch = hh[j]
        if ins:
            if esc: esc = False
            elif ch == '\\': esc = True
            elif ch == '"': ins = False
        else:
            if ch == '"': ins = True
            elif ch == o: d += 1
            elif ch == c:
                d -= 1
                if d == 0: return hh[s:j + 1]
    raise ValueError('unterminated: ' + decl)


def walk(node, path=()):
    """Every string in the db, with the path that reached it."""
    if isinstance(node, dict):
        for k, v in node.items():
            yield from walk(v, path + (str(k),))
    elif isinstance(node, list):
        for i, v in enumerate(node):
            yield from walk(v, path + (str(i),))
    elif isinstance(node, str):
        yield path, node


def main():
    h = SRC.read_text()
    stops = json.loads(ex(h, 'const STOPS =')) + json.loads(ex(h, 'const EXT_DATA =', '{', '}'))['STOPS']
    meta = {s['id']: (s.get('arrive') or '9999-99-99', s['name']) for s in stops}
    db = json.loads(DB.read_text())['stops']

    found = {}          # sid -> list of (what, number, where)
    for sid, entry in db.items():
        for path, text in walk(entry, ()):
            for num in set(PHONE.findall(text)):
                # The sentence the number sits in, so the call has a question.
                bits = re.split(r'(?<=[.!?])\s+', text)
                why = next((b for b in bits if num in b), text)
                found.setdefault(sid, []).append((why.strip(), num, '.'.join(path[:2])))

    # A stop whose authority publishes nothing is an open call even without a
    # number in the text — the action line says who to ring.
    for sid, entry in db.items():
        rec = entry.get('dogs_unpublished') or {}
        act = rec.get('action') or ''
        if act and not PHONE.search(act):
            found.setdefault(sid, []).append(
                (act.strip(), '—', 'dogs_unpublished'))

    rows = sorted(((meta.get(sid, ('9999-99-99', sid))[0], sid) for sid in found))

    out = ['# Calls that would close out open questions',
           '',
           'Generated by `tools/build_calls.py` from `links_db.json`. In arrival order —',
           'the only order that matters, since a call about a stop three weeks out is',
           'urgent in a way the same call two years out is not.',
           '',
           'Each line is a question the managing authority does not publish. They are not',
           'blockers: every one of them is recorded on the dashboard as unknown rather than',
           'guessed, which is the safe state. Making the call turns a blank into an answer.',
           '']
    seen_pairs = set()
    for arrive, sid in rows:
        name = meta.get(sid, (None, sid))[1]
        items = []
        for why, num, where in found[sid]:
            key = (sid, num, why[:60])
            if key in seen_pairs:
                continue
            seen_pairs.add(key)
            items.append((why, num, where))
        if not items:
            continue
        when = arrive if arrive != '9999-99-99' else 'no date'
        out.append(f'## {when} — {name}  `{sid}`')
        out.append('')
        for why, num, where in items:
            out.append(f'- **{num}** — {why}')
            out.append(f'  <sub>{where}</sub>')
        out.append('')

    text = '\n'.join(out)
    n = sum(len(v) for v in found.values())
    print(text)
    print(f'--- {len(found)} stops, {n} open items ---', file=sys.stderr)
    if '--write' in sys.argv:
        (HERE / 'CALLS.md').write_text(text)
        print('written to tools/CALLS.md', file=sys.stderr)


if __name__ == '__main__':
    main()
